kind: Template
apiVersion: v1
metadata:
  name: custom-build
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      annotations:
        description: Defines how to build the application
    spec:
      output:
        to:
          kind: ImageStreamTag
          description: 目标产品镜像的名字
          name: "${APPLICATION_NAME}:latest"
      source:
        type: Source
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "master"
        contextDir: "/"
      strategy:
        type: Source
        sourceStrategy:
          from:
            description: 产品镜像的箱子是谁在那个空间下
            kind: "ImageStreamTag"
            namespace: "openshift"
            name: 'tomcat8-jdk8:latest'
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
    spec:
      replicas: 1
      selector:
        name: "${APPLICATION_NAME}"
      template:
        metadata:
          labels:
            name: "${APPLICATION_NAME}"
        spec:
          containers:
          - image: "${APPLICATION_NAME}"
            name: "${APPLICATION_NAME}"
            ports:
            - containerPort: 8080
              protocol: TCP
parameters:
  - name: NEXUS_URL
    displayName: NEXUS url
    description: The URL of the repository with your war
    value: https://github.com/mclitao/mybank-demo-maven/raw/master/ROOT.war
    required: true
  - name: APPLICATION_NAME
    displayName: Application Name
    description: Application Name
    value: appname
    required: true
  - description: 放入包含ROOT.war文件的git地址
    displayName: Git Repository where you have the binaries
    name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/mclitao/mybank-demo-maven.git