# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: template.openshift.io/v1
kind: Template
message: 这里是部署完毕向导后的消息栏,添加一个根目录包含ROOT.war文件的git地址
  你的代码就会和这个tomcat镜像再次重新编译生成最终产品镜像
  最终输出你要的产品模板部署运行它.
metadata:
  annotations:
    description: 给他包含ROOT.war的git地址就可以编译运行了.
    iconClass: icon-tomcat
    tags: builder,java,base-centos7,jdk8,tomcate8,jee
    openshift.io/display-name: Tomcat 8.032 + Jdk 1.8.0
    openshift.io/provider-display-name: 'centos7 + jdk + tomat + war'
    version: 8.032
  name: tomcat8-jdk8
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${APP_NAME}:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
      secrets: []
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${BaseImageStream}
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: cK9NgyT9bMNAmmMjNi_7
      type: GitHub
    - generic:
        secret: EQ0d6gvPJz63eWAXkjSj
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${APP_NAME}
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- description: 放入包含ROOT.war文件的git地址
  displayName: Git Repository where you have the binaries
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/debianmaster/sample-binaries.git
- description: 给你的应用起一个名字
  displayName: Application Name
  name: APP_NAME
  required: true
  value: tomcat8-jdk8-war-app
- description: 编译代码的基础容器盒子:version
  displayName: Base ImageStream:version
  name: BaseImageStream
  required: true
  value: tomcat8-jdk8:latest